version: '3'

services:
  rest:
    build: "W1-REST-Service/."
    ports:
      - "9090:8080"
  soap:
    build: "W1-SOAP-Service/."
    ports:
      - "7079:8080"
  restdos:
    build: "W1-REST-Service-SpringBoot/."
    ports:
      - "7071:8080"
  #Base de datos
  mysql-dev: 
    image : mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogapp
    ports:
      - "3306:3306"
  #Administrar base de datos
  admin:
   image : adminer
   ports:
     - "8081:8080"
  #Llamar inicial
  consultabd:
    build: "W1-BD/."
    ports:
      - "7075:8080"
  orq:
    build: "W1-REST-OR/."
    ports:
      - "7077:8080" 
  transrest:
    build: "W1-REST-TRANSFORMACION/."
    ports:
      - "7078:8080"
  transsoap:
    build: "W1-SOAP-TRANSFORMACION/."
    ports:
      - "7173:8080"   
      
